import { ContactApiDto, EmailAddressApiDto } from '../models/api.dto';



export const MOCK_CONTACTS: ContactApiDto[] = [
  {
    id: '1',
    first_name: 'Nicholas',
    last_name: 'Gordon',
    job_title: 'Developer',
    company: 'TechCorp',
    avatar: undefined,
    status: 'online',
    bio: 'Full-stack developer passionate about clean architecture and test-driven development.',
    address: '12 Baker Street, London, UK',
    phone: '555-012-3456',
    phone_secondary: '555-098-7654',
    social_linkedin: 'linkedin.com/in/nicholasgordon',
    social_twitter: 'twitter.com/ngordon',
    meeting_link: 'https://meet.example.com/nicholas',
    dial_in: 'n.gordon@ymsg.com',
    created_at: '2023-01-15T08:00:00Z',
  },
  {
    id: '2',
    first_name: 'Bradley',
    last_name: 'Malone',
    job_title: 'Sales Manager',
    company: 'SalesForce Inc.',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    status: 'away',
    bio: 'Results-driven sales professional with 10+ years of enterprise SaaS experience.',
    address: '45 Elm Avenue, New York, USA',
    phone: '555-234-5678',
    social_linkedin: 'linkedin.com/in/bradleymalone',
    social_facebook: 'facebook.com/bradleymalone',
    meeting_link: 'https://meet.example.com/bradley',
    dial_in: 'b.malone@ymsg.com',
    created_at: '2023-02-10T09:30:00Z',
  },
  {
    id: '3',
    first_name: 'Johanna',
    last_name: 'Stevens',
    job_title: 'UI/UX Designer',
    company: 'WhiteUI Studio',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    status: 'online',
    bio: 'When I first got into the advertising, I was looking for the magical combination that would put website into the top search engine rankings.',
    address: '78 Design Lane, San Francisco, USA',
    phone: '439-582-1578',
    phone_secondary: '621-770-7689',
    social_facebook: 'facebook.com/johanna.stevens',
    social_twitter: 'twitter.com/jstevens',
    social_linkedin: 'linkedin.com/in/johanna-stevens',
    social_instagram: 'instagram.com/jstevensdesign',
    meeting_link: 'http://go.betacall.com/meet/j.stevens',
    dial_in: 'j.stevens@ymsg.com',
    created_at: '2023-03-05T10:00:00Z',
  },
  {
    id: '4',
    first_name: 'Marvin',
    last_name: 'Lambert',
    job_title: 'Designer',
    company: 'Creative Labs',
    avatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    status: 'offline',
    bio: 'Visual storyteller with expertise in brand identity and motion design.',
    address: '23 Art Street, Chicago, USA',
    phone: '555-345-6789',
    social_instagram: 'instagram.com/marvinlambert',
    meeting_link: 'https://meet.example.com/marvin',
    dial_in: 'm.lambert@ymsg.com',
    created_at: '2023-03-20T11:00:00Z',
  },
  {
    id: '5',
    first_name: 'Teresa',
    last_name: 'Lloyd',
    job_title: 'PR Agent',
    company: 'MediaLink',
    avatar: undefined,
    status: 'away',
    bio: 'Strategic communications expert helping brands find their voice in the digital age.',
    address: '90 Media Row, Los Angeles, USA',
    phone: '555-456-7890',
    social_twitter: 'twitter.com/teresalloyd',
    social_linkedin: 'linkedin.com/in/teresalloyd',
    meeting_link: 'https://meet.example.com/teresa',
    dial_in: 't.lloyd@ymsg.com',
    created_at: '2023-04-01T12:00:00Z',
  },
  {
    id: '6',
    first_name: 'Fred',
    last_name: 'Haynes',
    job_title: 'Support Engineer',
    company: 'HelpDesk Pro',
    avatar: 'https://randomuser.me/api/portraits/men/55.jpg',
    status: 'online',
    bio: 'Dedicated customer support specialist with a knack for solving complex technical issues.',
    address: '55 Support Ave, Austin, USA',
    phone: '555-567-8901',
    phone_secondary: '555-111-2222',
    social_linkedin: 'linkedin.com/in/fredhaynes',
    meeting_link: 'https://meet.example.com/fred',
    dial_in: 'f.haynes@ymsg.com',
    created_at: '2023-04-15T09:00:00Z',
  },
  {
    id: '7',
    first_name: 'Rose',
    last_name: 'Peters',
    job_title: 'Project Manager',
    company: 'AgileWorks',
    avatar: 'https://randomuser.me/api/portraits/women/62.jpg',
    status: 'online',
    bio: 'Certified PMP driving cross-functional teams to deliver on time and within budget.',
    address: '33 Project Blvd, Seattle, USA',
    phone: '555-678-9012',
    social_linkedin: 'linkedin.com/in/rosepeters',
    social_twitter: 'twitter.com/rpeters_pm',
    meeting_link: 'https://meet.example.com/rose',
    dial_in: 'r.peters@ymsg.com',
    created_at: '2023-05-01T08:30:00Z',
  },
  {
    id: '8',
    first_name: 'Brian',
    last_name: 'Watson',
    job_title: 'Developer',
    company: 'DevStudio',
    avatar: undefined,
    status: 'online',
    bio: 'Backend engineer specialising in distributed systems and cloud infrastructure.',
    address: '18 Code Street, Denver, USA',
    phone: '555-789-0123',
    social_linkedin: 'linkedin.com/in/brianwatson',
    meeting_link: 'https://meet.example.com/brian',
    dial_in: 'b.watson@ymsg.com',
    created_at: '2023-05-10T10:00:00Z',
  },
  {
    id: '9',
    first_name: 'Hettie',
    last_name: 'Richardson',
    job_title: 'Developer',
    company: 'PixelByte',
    avatar: undefined,
    status: 'online',
    bio: 'Frontend architect focused on performance, accessibility, and design systems.',
    address: '67 Tech Park, Boston, USA',
    phone: '555-890-1234',
    social_linkedin: 'linkedin.com/in/hettierichardson',
    social_twitter: 'twitter.com/hrichardson_dev',
    meeting_link: 'https://meet.example.com/hettie',
    dial_in: 'h.richardson@ymsg.com',
    created_at: '2023-06-01T07:45:00Z',
  },
  {
    id: '10',
    first_name: 'Samuel',
    last_name: 'Chen',
    job_title: 'Data Analyst',
    company: 'DataViz Co.',
    avatar: 'https://randomuser.me/api/portraits/men/72.jpg',
    status: 'offline',
    bio: 'Turning complex datasets into actionable business insights through data storytelling.',
    address: '29 Analytics Way, Portland, USA',
    phone: '555-901-2345',
    social_linkedin: 'linkedin.com/in/samuelchen',
    meeting_link: 'https://meet.example.com/samuel',
    dial_in: 's.chen@ymsg.com',
    created_at: '2023-06-15T11:00:00Z',
  },
];

/**
 * Mock email addresses keyed by contact ID.
 * Simulates /contacts/{id}/email_addresses endpoint.
 */
export const MOCK_EMAIL_ADDRESSES: Record<string, EmailAddressApiDto[]> = {
  '1': [
    { id: 'e1a', contact_id: '1', email: 'nicholas.gordon@techcorp.com', is_primary: true, label: 'Work' },
    { id: 'e1b', contact_id: '1', email: 'ngordon.personal@gmail.com', is_primary: false, label: 'Personal' },
  ],
  '2': [
    { id: 'e2a', contact_id: '2', email: 'bradley.malone@salesforce.com', is_primary: true, label: 'Work' },
  ],
  '3': [
    { id: 'e3a', contact_id: '3', email: 'johanna.stevens@gmail.com', is_primary: true, label: 'Personal' },
    { id: 'e3b', contact_id: '3', email: 'johanna.stevens@whiteui.store', is_primary: false, label: 'Work' },
  ],
  '4': [
    { id: 'e4a', contact_id: '4', email: 'marvin.lambert@creativelabs.io', is_primary: true, label: 'Work' },
  ],
  '5': [
    { id: 'e5a', contact_id: '5', email: 'teresa.lloyd@medialink.com', is_primary: true, label: 'Work' },
    { id: 'e5b', contact_id: '5', email: 'teresa.pr@gmail.com', is_primary: false, label: 'Personal' },
  ],
  '6': [
    { id: 'e6a', contact_id: '6', email: 'fred.haynes@helpdeskpro.com', is_primary: true, label: 'Work' },
  ],
  '7': [
    { id: 'e7a', contact_id: '7', email: 'rose.peters@agileworks.com', is_primary: true, label: 'Work' },
    { id: 'e7b', contact_id: '7', email: 'rosepm@outlook.com', is_primary: false, label: 'Personal' },
  ],
  '8': [
    { id: 'e8a', contact_id: '8', email: 'brian.watson@devstudio.com', is_primary: true, label: 'Work' },
  ],
  '9': [
    { id: 'e9a', contact_id: '9', email: 'hettie.richardson@pixelbyte.io', is_primary: true, label: 'Work' },
    { id: 'e9b', contact_id: '9', email: 'hettie.dev@gmail.com', is_primary: false, label: 'Personal' },
  ],
  '10': [
    { id: 'e10a', contact_id: '10', email: 'samuel.chen@dataviz.co', is_primary: true, label: 'Work' },
  ],
};
